export const ACTION_TYPES = {
  DISPLAY_NAME: 'DISPLAY_NAME',
  DISPLAY_COUNTRY: 'DISPLAY_COUNTRY',
  HANDLE_PAGINATION: 'HANDLE_PAGINATION',
  HANDLE_REGION: 'HANDLE_REGION',
  HANDLE_SEARCH_BY_NAME: 'HANDLE_SEARCH_BY_NAME',
}